baseURL = "https://jimmyroland.com/"
languageCode = "en-us"
title = "Jimmy Roland"
theme = "hugo-initio"

[params]
    name = "Jimmy Roland"
    description = "Software Engineer"
    email = "jimmylroland@gmail.com"
    showSubheader = true
    showServices = true
    #showRecentWorks = true
    #showDownload = true
    #showClients = true
    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

    DateForm = "January 2, 2006"

[params.google.analytics]
    trackerID = "UA-113898347-1"

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
  name = "blog"
  url = "https://blog.jimmyroland.com"
  weight = 2

[[params.social]]
	title = "twitter"
	url = "https://twitter.com/includejimmy"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/jimmyroland"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true 
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/rukamir"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"
